# -*- coding: utf-8 -*-
"""Sort_data_cici.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PZekxLNXrR3FVWt_uZXqwkkbrnBgECgR
"""
import pandas as pd

data = pd.read_csv('result/hyperparameter.csv',delimiter=',',names=['A', 'B', 'C', 'D', 'RMSE','MAPE'])

high_rmse = data.sort_values(['RMSE'], ascending=True).head(10)
high_mape = data.sort_values(['MAPE'], ascending=True).head(10)
print(high_rmse)
print("High RMSE:")
print("Epoch      -->", high_rmse['A'].head(1))
print("Batch Size -->", high_rmse['B'].head(1))
print("Neuron     -->", high_rmse['C'].head(1))
print("Rasio      -->", high_rmse['D'].head(1))
print("RMSE       -->", high_rmse['RMSE'].head(1))
print("MAPE       -->", high_rmse['MAPE'].head(1))
print("------------------------------------------------------")

print(high_mape)
print("High MAPE:")
print("Epoch      -->", high_mape['A'].head(1))
print("Batch Size -->", high_mape['B'].head(1))
print("Neuron     -->", high_mape['C'].head(1))
print("Rasio      -->", high_mape['D'].head(1))
print("RMSE       -->", high_mape['RMSE'].head(1))
print("MAPE       -->", high_mape['MAPE'].head(1))
print("------------------------------------------------------")

